name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.82.1
        TARGET_REPO: li-tianxing/li-tianxing.github.io
        TARGET_BRANCH: master
        TOKEN: ${{ secrets.WOW_AUTO_DEPLOY_TOKEN }}
        CNAME: li-tianxing.github.io